[project]
name = "intro-to-prefect"
description = "An introductory project to Prefect"
version = "0.1.0"
requires-python = ">=3.12"
authors = [
    { name = "Ganesh Lokhande", email = "lokhandeganesh8@gmail.com" }
]
dependencies = [
    "prefect",
    "httpx",
    "psycopg2-binary"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-env",
    "pre-commit"

]

[project.scripts]
pipeline = "pipeline.main:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "pipeline"
